apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: example-app
  name: example-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example-app
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: docker.io/openshift/deployment-example:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          protocol: TCP
